version: '3.8'

services:
  web:
    build: ./youtube
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./youtube/:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
    depends_on:
      - redis
  redis:
    image: redis:alpine
  celery:
    build: ./youtube
    command: celery -A youtube worker -l info
    volumes:
      - ./youtube/:/usr/src/app/
    environment:
      - DEBUG=1
    depends_on:
      - redis
  celery-beat:
    build: ./youtube
    command: celery -A youtube beat -l info
    volumes:
      - ./youtube/:/usr/src/app/
    environment:
      - DEBUG=1
    depends_on:
      - redis