# Generated by Django 3.2 on 2021-04-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4096)),
                ('description', models.TextField(null=True)),
                ('thumbnail', models.URLField()),
                ('datetime', models.DateTimeField()),
                ('query', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
